language: node_js
node_js:
  - '8'
  - '9'
  - '10'

cache:
  yarn: true,
  directories:
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages

before_install:
  - npm install elm --global
